### ISSUE TITLE
Error while connecting to a containrized Elasticsearch instance

### ISSUE THREAD

**Issue by baseely** [elastic/elasticsearch-py#1926]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 7.4.0, Build: default/docker/22e1767283e61a198cb4db791ea66e3f11ab9910/2019-09-27T08:36:48.569419Z, JVM: 13

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 
7.7.0

Please make sure the major version matches the Elasticsearch server you are running.
Same major version (i.e. **7**)

**Description of the problem including expected versus actual behavior**:
When connecting to an Elasticsearch instance running inside a Docker container I get this error message:
`missing 1 required positional argument: 'scheme' `

**Steps to reproduce**:
1- I am using the below **docker-compose** to pull the Elasticsearch image, so create a file and name it "elasticsearch-compose.yml" with the below:
```
version: "3.3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
```
   
2- run `docker-compose -f elasticsearch-compose.yml`
3- Run a Python client with the blow code:
```
from elasticsearch import Elasticsearch
class Elastic:
    def __init__(self):
        self.host = "x.y.x.w" # Already added my VM IP address 
        self.port = 9200
        self.es = None
        self.connect()

    def connect(self):
        self.es = Elasticsearch({'host': self.host, 'port': self.port})
```

Stacktrace:
```
Exception has occurred: TypeError
__init__() missing 1 required positional argument: 'scheme'
  File "[C:\Users\MyUserName\elasticsearch-python-demo.py]()", line 20, in connect`
    self.es = Elasticsearch({'host': self.host, 'port': self.port})
  File "[C:\Users\MyUserName\elasticsearch-python-demo.py]()", line 15, in __init__
    self.connect()
```
I bypass this error by adding the below to my code:
```
    ..

    def connect(self):
        self.es = Elasticsearch({'host': self.host, 'port': self.port, 'scheme': 'http'})
```
but it doesn't connect and when checking the [ping](https://elasticsearch-py.readthedocs.io/en/v7.13.0/api.html?highlight=ping#elasticsearch.Elasticsearch.ping) method it returns `False` instead of `True` !
